######################################################################
# Automatically generated by qmake (3.0) Thu Jul 19 01:33:39 2018
######################################################################
QT_VERSION = 5

TEMPLATE = app
TARGET = spreadsheet
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += cell.h mainwindow.h spreadsheet.h
SOURCES += cell.cpp main.cpp mainwindow.cpp spreadsheet.cpp
