######################################################################
# Automatically generated by qmake (3.0) Thu Jul 19 01:46:08 2018
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += hello.cpp
