######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 10 17:01:33 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += layout.cpp
