######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 10 23:39:06 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
