######################################################################
# Automatically generated by qmake (3.0) Thu Jul 19 01:41:32 2018
######################################################################

TEMPLATE = app
TARGET = finddialog
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
