######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 10 15:29:29 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
